// Jest test globals
declare const describe: jest.Describe;
declare const it: jest.It;
declare const test: jest.It;
declare const before: jest.Lifecycle;
declare const after: jest.Lifecycle;
declare const beforeEach: jest.Lifecycle;
declare const afterEach: jest.Lifecycle;
declare const expect: jest.Expect;